name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: install
        run: npm ci

      - name: lint
        run: npm run lint

      - name: compile
        run: npm run compile

      - name: test with coverage
        run: npm run test:cov
