name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 22, 24]
        module_type: ['cjs', 'esm']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: install
        run: pnpm install

      - name: lint
        run: pnpm run lint

      - name: build
        run: pnpm run build

      - name: test with coverage
        run: pnpm run test:cov

      - name: bundle
        run: pnpm run bundle --withDeps

      - name: check bundle coverage
        run: pnpm run bundle:cov

      # integration test
      - name: integration install
        working-directory: test-int/${{ matrix.node }}-${{ matrix.module_type }}
        run: npm install

      - name: integration build
        working-directory: test-int/${{ matrix.node }}-${{ matrix.module_type }}
        run: npm run build

      - name: integration test
        working-directory: test-int/${{ matrix.node }}-${{ matrix.module_type }}
        run: npm run test
