name: Publish


on:
  workflow_dispatch:
    inputs:
      version:
        description: version to publish
        required: true
      otp:
        description: one time password
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version: 22
          cache: pnpm

      - name: configure git
        run: |
          git config --global user.name 'Romain Prignon'
          git config --global user.email 'pro.rprignon@gmail.com'

      - name: install
        run: pnpm install

      - name: version
        run: pnpm run version:${{ github.event.inputs.version }}

      - name: deploy
        run: pnpm run deploy -- --otp ${{ github.event.inputs.otp }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
